### ISSUE TITLE
Issue with using different envioronment variable except BLOB_READ_WRITE_TOKEN

### ISSUE THREAD

**Issue by andershermansen** [JarvisPrestidge/payload-cloud-storage-vercel-adapter#12]
I wanted to use this plugin with two different collections with different connections.
So I configured different instances of it with different tokens and storeid.

When using it I got this error message:
```
ERROR: Vercel Blob: No token found. Either configure the `BLOB_READ_WRITE_TOKEN` environment variable, or pass a `token` option to your calls.
    err: {
      "type": "BlobError",
      "message": "Vercel Blob: No token found. Either configure the `BLOB_READ_WRITE_TOKEN` environment variable, or pass a `token` option to your calls.",
      "stack":
...
    }
```

It seems because one usage of vercel blob (head) is not passing the token.

**Comment by andershermansen** [comment]
Fix in PR https://github.com/JarvisPrestidge/payload-cloud-storage-vercel-adapter/pull/13

**Comment by JarvisPrestidge** [comment]
#13 merged and a new release is being authored, thank you for the contribution!
